##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    CORENAME: mu
    JNI_PATH: libretroBuildSystem

# Post extends for mu
.mu-post-common:
  variables:
    MAKEFILE_PATH: libretroBuildSystem
    MAKEFILE: Makefile.libretro

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

  ################################## CONSOLES ################################
  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'

  # PLayStation 2
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ps2-static.yml'

  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
    - .mu-post-common

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
    - .mu-post-common

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .core-defs
    - .libretro-osx-x64-make-default
    - .mu-post-common

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .core-defs
    - .libretro-android-jni-armeabi-v7a
    - .mu-post-common

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .core-defs
    - .libretro-android-jni-arm64-v8a
    - .mu-post-common

# Android 64-bit x86
android-x86_64:
  extends:
    - .core-defs
    - .libretro-android-jni-x86_64
    - .mu-post-common

# Android 32-bit x86
android-x86:
  extends:
    - .core-defs
    - .libretro-android-jni-x86
    - .mu-post-common

################################### CONSOLES #################################
# Nintendo Switch
libretro-build-libnx-aarch64:
  extends:
    - .core-defs
    - .libretro-libnx-static-retroarch-master
    - .mu-post-common

# PlayStation 2
libretro-build-ps2:
  extends:
    - .core-defs
    - .libretro-ps2-static-retroarch-master
    - .mu-post-common

# PlayStation Vita
libretro-build-vita:
  extends:
    - .core-defs
    - .libretro-vita-static-retroarch-master
    - .mu-post-common
